CREATE TABLE tags (
    id BIGSERIAL PRIMARY KEY,
    tag_name VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE task_tag (
    task_id BIGINT NOT NULL REFERENCES tasks(id),
    tag_id BIGINT NOT NULL REFERENCES tags(id),
    PRIMARY KEY (task_id, tag_id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);